### ISSUE TITLE
helloworld-scene sample project has very low framerate on Pixel 4a

### ISSUE THREAD

**Issue by peterstuart** [NativeVision/virocore#1]
## Environment
Please provide the following information about your environment:
1. OS: Mac, Linux
2. Version: 1.17.0 
3. Device(s): Pixel 4a

## Description
The virocode-helloworld-scene sample project (https://s3-us-west-2.amazonaws.com/virocore/1_17_0/virocore-helloworld.zip) runs at ~1 fps. The virocode-helloworld-ar sample project included in the same file runs much faster. These are the sample projects linked from [this page](https://virocore.viromedia.com/docs/getting-started). Is there some additional configuration needed to get the scene example to run properly?

Thanks!

**Comment by itslonua** [comment]
@peterstuart The background image & hdr effect has been disabled. Frame rate is ~2fps on the high-poly scenes.
