### ISSUE TITLE
Virocore crashing in 32 bit (armeabi-v7a) android devices with Fatal signal 7 SIGBUS error

### ISSUE THREAD

**Issue by ajayjohn2021** [NativeVision/virocore#71]
## Environment-
1. OS: Linux
2. Version: ViroCore release rc-1.20.2 
3. Device(s): Redmi 9i, Redmi 7A

## Description-

Virocore crashes in 32-bit Android devices
Even when trying to display a sample gltf model, virocore crashes with this error-
Fatal signal 7 (SIGBUS), code 1 (BUS_ADRALN), fault addr 0xc3d94a1c in tid 18557 (GLThread 128916), pid 18514

This seems to be from a data alignment problem according to a lot of StackOverflow answers and this reference https://www-uxsup.csx.cam.ac.uk/courses/moved.Building/signals.pdf

Findings:
-When I looked in the aar file there were .so files present for both armeabi-v7a(32 bit) and arm64-v8a(64bit), in a jni folder
-In the old viromedia git there seems to be an issue where 64 bit isn't working but 32 is (https://github.com/viromedia/virocore/issues/43)

## Reproducible Demo

1) Check whether your device is running in 32 bit mode using Aida64 app, in Cpu-> Instruction sets

![Screenshot from 2022-02-03 15-44-50](https://user-images.githubusercontent.com/89006096/152326901-6e9d5087-ef43-4895-a179-4f61e0baf1f8.png)
![Screenshot from 2022-02-03 10-53-09](https://user-images.githubusercontent.com/89006096/152326923-201cace3-0a2e-4370-ae34-22ce7ead8631.png)

2) Download virocore(virocore-release.aar) release from https://github.com/ViroCommunity/virocore/releases (I've tried rc-1.20.2 and rc-1.20.1)

3) Start a new project in android studio (ensure minsdk is 24 for virocore)

4) Place virocore-release.aar in the libs folder

5) Add it in the module level build.gradle file with - implementation files('libs/virocore-release.aar')
	
6) Place box.gltf in the assets folder(https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/Box/glTF-Embedded/Box.gltf), or if using a different file ensure that the path and type in loadModel function is matching

7) Replace default class with following code:-

```
class MainActivity : AppCompatActivity() {

    private lateinit var mViroView: ViroViewScene
    private lateinit var cameraNode: Node

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        mViroView = ViroViewScene(this, object : ViroViewScene.StartupListener {
            override fun onSuccess() {
                showBox()
            }

            override fun onFailure(startupError: ViroViewScene.StartupError, s: String) {
            }
        })

        setContentView(mViroView)
    }

    private fun showBox()
    {
        val scene = Scene()
        val rootNode = scene.rootNode
        rootNode.setPosition(Vector(0.0, 0.0, 0.0))

        val model = Object3D()
        model.loadModel(
            mViroView.viroContext,
            Uri.parse("file:///android_asset/box.gltf"),
            Object3D.Type.GLTF,
            object : AsyncObject3DListener {
                override fun onObject3DFailed(error: String) {
                    Log.e("showBox", "Failed to load!")
                }

                override fun onObject3DLoaded(`object`: Object3D, type: Object3D.Type) {
                    Log.e("showBox", "Model loaded!")
                }
            })
        rootNode.addChildNode(model)

        val ambient = AmbientLight(Color.WHITE.toLong(), 800.0f)
        rootNode.addLight(ambient)

        cameraNode = Node()
        val camera = Camera()
        cameraNode.setPosition(Vector(0.0, 1.0, 10.0))
        cameraNode.camera = camera
        rootNode.addChildNode(cameraNode)

        mViroView.scene = scene
        mViroView.setPointOfView(cameraNode)
        mViroView.setDebug(true)
    }
}
```

8) Ensure that Vector, Scene, etc. imports are from virocore

9) Run the project on your device(not emulator)

If your device is 64 bit it should display a red cube, else it should crash
Main error : Fatal signal 7 (SIGBUS), code 1 (BUS_ADRALN), fault addr 0xc3d94a1c in tid 18557 (GLThread 128916), pid 18514

If I have made any mistakes, please do point them out, any help/input is appreciated!

**Comment by robertjcolley** [comment]
Unfortunately, this is a wontfix issue. We rely on AR Core which has a 64 bit requirement. See https://developers.google.com/ar/64bit for more
